import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useEffect, useState } from 'react'
import BagIcon from './components/icons/BagIcon'
import BuyIcon from './components/icons/BuyIcon'
import Star from './components/icons/StarIcon'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [products, setProducts] = useState([])

  useEffect(() => {
    async function fetchData() {
      const res = await fetch('https://dummyjson.com/products',
        {
          method: 'GET',
          headers: {
            "Content-Type": "application/json",
          },
        }
      )
      let data = await res.json()
      // console.log(data.products)
      // res.then((data) => data.json())
      //   .then((data) =>
      //     // console.log(data.products)
      setProducts(data.products)
      //   )
    }
    fetchData()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='mx-auto max-w-3xl'>
          <section id="products" className='grid grid-cols-3 gap-5'>
            {
              products && products.map((product, index) => {
                return (
                  <div key={index} className="w-full shadow p-4 relative">
                    <button title='add to cart' className="bg-gray-700 absolute top-10 left-0 p-2 rounded-br-lg rounded-r-lg hover:p-4 transition-all text-white z-10">
                      <BagIcon />
                    </button>
                    <button title='buy now' className="bg-gray-700 absolute top-24 left-0 p-2 rounded-br-lg rounded-r-lg hover:p-4 transition-all text-white z-10">
                      <BuyIcon />
                    </button>
                    <a href={`/product/${product.id}`} className=''>
                      <div className="relative">
                        <img src={product.thumbnail} alt="Product Thumbnail" className='w-80 h-56 object-fill' />
                      </div>
                      <h3 className="text-xl">{product.title}</h3>
                      <div className="flex justify-between items-center">
                        <p className="">
                          <span className="bg-gray-300 rounded-full px-2 py-1 text-gray-50 mb-1 text-[12px]">
                            {product.category}
                          </span>
                          <span className="flex items-center">
                            <Star /><small className='text-[12px]'>{Number(product.rating).toFixed(2)}</small>
                          </span>
                        </p>
                        <p className="flex flex-col">
                          <span className="text-base">
                            {Number(product.price).toFixed(2)}
                          </span>
                          <span className="text-sm line-through">
                            {Number(product.price * product.discountPercentage).toFixed(2)}
                          </span>
                        </p>
                      </div>
                    </a>

                  </div>
                )
              })
            }
          </section>

        </div>
      </main>
    </>
  )
}
